name: Deploy Dist

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print Node Version
        run: node -v

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
